export default [
  {
    id: 'not-humble',
    title: '222',
    path: '/projects/not-humble',
    video: 'featured-video.mp4',
  },
  {
    id: 'not-humble',
    title: 'AD3',
    path: '/projects/not-humble',
    video: 'featured-video.mp4',
  },
  {
    id: 'bleeping-easy',
    title: 'Big C',
    path: '/projects/bleeping-easy',
    video: 'easy.mp4',
  },
  {
    id: 'bleeping-easy',
    title: 'Big Skepp',
    path: '/projects/bleeping-easy',
    video: 'easy.mp4',
  },
  {
    id: 'bleeping-easy',
    title: 'BMF. Mike',
    path: '/projects/bleeping-easy',
    video: 'easy.mp4',
  },
  {
    id: 'bleeping-easy',
    title: 'Boy Blark',
    path: '/projects/bleeping-easy',
    video: 'easy.mp4',
  },
  {
    id: 'make-it-zero',
    title: 'Cain',
    path: '/projects/make-it-zero',
    video: 'make-it-zero.mp4',
  },
  {
    id: 'it-takes-an-island',
    title: 'Chucks',
    path: '/projects/it-takes-an-island',
    video: 'it-takes-an-island.mp4',
  },
  {
    id: '50-beaches',
    title: 'Damiro baker',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Danito',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Gremlin',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Itj',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Jiggy',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Max',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Rocket-man',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Magnus',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'SBA',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Slheem',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'Shy-boy',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
  {
    id: '50-beaches',
    title: 'TBA',
    path: '/projects/50-beaches',
    video: '50-beaches.mp4',
  },
];
