export default [
  [
    'Strategy & Development',
    [
      'Creative Development',
      'Creative Writing',
      'Storyboards',
      'Art Direction',
      'Creative Direction',
      'Location Scouting',
      'Influencer & Talent Network',
      'Social Content',
      'Content Strategy',
      'Casting',
    ],
  ],
  [
    'Video Production',
    [
      'Principle Photography',
      'Production Management',
      'Crew',
      'Gear Rental',
      'LTO-Archiving',
    ],
  ],
  [
    'Product-Design & Dev',
    [
      'User Experience Design',
      'Graphic Design',
      'Product Development',
      'Ecommerce Development',
      'Supplier and manufacturing Network',
      'Brand design and development of physical products',
    ],
  ],
  [
    'Post-Production/Design',
    [
      'Colour correction',
      'Offline editing',
      'Online editing',
      'VFX',
      'Animation and motion graphics',
      'Closed captioning and subtitles',
      'Descriptive video',
      'Dailies',
      'Quality control',
      'LTO Archiving',
    ],
  ],
  [
    'Audio Post-Production',
    [
      'We work with some amazing membahs who provide:',
      'Sound Design',
      'SFX',
      'Music',
      'Song writing',
      'Music scoring',
      'Sound Mix',
    ],
  ],
  [
    'Products activation & Experiences',
    [
      'Experiential activations/marketing',
      'Event production',
      'Brand activations',
      'Space design & set build',
      'Sponsorship alignment and management',
      'talent booking and management',
      'Experiential content production',
    ],
  ],
];
